UsersTracker/Controllers/ClientProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UsersTracker.Entities;
using UsersTracker.Models;

namespace UsersTracker.Controllers
{
    public class ClientProductsController : Controller
    {
        private UsersTrackerContext db = new UsersTrackerContext();

        // GET: ClientProducts
        public async Task<ActionResult> Index()
        {
            var clientProducts = db.ClientProducts.Include(c => c.Client).Include(c => c.Product);
            return View(await clientProducts.ToListAsync());
        }

        // GET: ClientProducts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClientProduct clientProduct = await db.ClientProducts.FindAsync(id);
            if (clientProduct == null)
            {
                return HttpNotFound();
            }
            return View(clientProduct);
        }

        // GET: ClientProducts/Create
        public ActionResult Create()
        {
            ViewBag.IdClient = new SelectList(db.Clients, "Id", "Firstname");
            ViewBag.IdProduct = new SelectList(db.Products, "Id", "Name");
            ClientProduct cp = new ClientProduct();
            cp.BuyAt = DateTime.Now;
            return View(cp);
        }

        // POST: ClientProducts/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,IdClient,IdProduct,Number,BuyAt")] ClientProduct clientProduct)
        {
            if (ModelState.IsValid)
            {
                clientProduct.Client = await db.Clients.Include(x => x.Compte).FirstOrDefaultAsync(x => x.Id == clientProduct.IdClient);
                clientProduct.Product = await db.Products.Include(x => x.Enseigne).FirstOrDefaultAsync(x => x.Id == clientProduct.IdProduct);

                clientProduct.Client.Compte.Solde -= clientProduct.Product.Price * clientProduct.Number;

                if (clientProduct.Client.Compte.Solde >= 0)
                {
                    db.Entry(clientProduct.Client.Compte).State = EntityState.Modified;
                    db.ClientProducts.Add(clientProduct);
                    await db.SaveChangesAsync();

                    ClientEnseigne cliEn = new ClientEnseigne();
                    cliEn.Client = clientProduct.Client;
                    cliEn.IdClient = clientProduct.Client.Id;
                    cliEn.Enseigne = clientProduct.Product.Enseigne;
                    cliEn.IdEnseigne = clientProduct.Product.Enseigne.Id;
                    db.ClientEnseignes.Add(cliEn);
                    await db.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "Vous ne possédez pas les fond nécessaire";
                }
                
            }

            ViewBag.IdClient = new SelectList(db.Clients, "Id", "Firstname", clientProduct.IdClient);
            ViewBag.IdProduct = new SelectList(db.Products, "Id", "Name", clientProduct.IdProduct);
            return View(clientProduct);
        }

        // GET: ClientProducts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClientProduct clientProduct = await db.ClientProducts.FindAsync(id);
            if (clientProduct == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdClient = new SelectList(db.Clients, "Id", "Firstname", clientProduct.IdClient);
            ViewBag.IdProduct = new SelectList(db.Products, "Id", "Name", clientProduct.IdProduct);
            return View(clientProduct);
        }

        // POST: ClientProducts/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,IdClient,IdProduct,Number,BuyAt")] ClientProduct clientProduct)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clientProduct).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.IdClient = new SelectList(db.Clients, "Id", "Firstname", clientProduct.IdClient);
            ViewBag.IdProduct = new SelectList(db.Products, "Id", "Name", clientProduct.IdProduct);
            return View(clientProduct);
        }

        // GET: ClientProducts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClientProduct clientProduct = await db.ClientProducts.FindAsync(id);
            if (clientProduct == null)
            {
                return HttpNotFound();
            }
            return View(clientProduct);
        }

        // POST: ClientProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ClientProduct clientProduct = await db.ClientProducts.FindAsync(id);
            db.ClientProducts.Remove(clientProduct);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UsersTracker/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UsersTracker.Entities;
using UsersTracker.Models;
using UsersTracker.Entities.Utils;

namespace UsersTracker.Controllers
{
    public class ClientsController : Controller
    {
        private UsersTrackerContext db = new UsersTrackerContext();

        // GET: Clients
        public async Task<ActionResult> Index()
        {
            return View(await db.Clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Client client = await db.Clients.Include(x => x.Compte).FirstOrDefaultAsync(x => x.Id == id);

            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Clients/Create
        public async Task<ActionResult> Create()
        {
            return View();
        }

        // POST: Clients/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ClientCompte clientCompte)
        {
            if (ModelState.IsValid)
            {
                clientCompte.Client.Compte = clientCompte.Compte;
                db.Clients.Add(clientCompte.Client);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(clientCompte);
        }

        // GET: Clients/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClientCompte clientCompte = new ClientCompte();
            clientCompte.Client = await db.Clients.FindAsync(id);
            clientCompte.Client = await db.Clients.Include(x => x.Compte).FirstOrDefaultAsync();
            if (clientCompte == null)
            {
                return HttpNotFound();
            }
            return View(clientCompte);
        }

        // POST: Clients/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ClientCompte clientCompte)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clientCompte.Client.Compte).State = EntityState.Modified;
                await db.SaveChangesAsync();
                db.Entry(clientCompte.Client).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(clientCompte);
        }

        // GET: Clients/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = await db.Clients.FindAsync(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Client client = await db.Clients.FindAsync(id);
            db.Clients.Remove(client);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UsersTracker/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UsersTracker.Entities;
using UsersTracker.Models;
using UsersTracker.Entities.Utils;

namespace UsersTracker.Controllers
{
    public class ProductsController : Controller
    {
        private UsersTrackerContext db = new UsersTrackerContext();

        // GET: Products
        public async Task<ActionResult> Index()
        {
            return View(await db.Products.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.Include(x => x.Enseigne).FirstOrDefaultAsync(x => x.Id == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public async Task<ActionResult> Create()
        {
            ProductEnseigneList prodEnL = new ProductEnseigneList();
            prodEnL.Enseignes = await db.Enseignes.ToListAsync();
            return View(prodEnL);
        }

        // POST: Products/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductEnseigneList productEnseigneList)
        {
            try
            {
                if (productEnseigneList.Enseigne != null && productEnseigneList.Product.Price != null)
                {
                    productEnseigneList.Product.Enseigne = await db.Enseignes.FindAsync(productEnseigneList.Enseigne);
                    db.Products.Add(productEnseigneList.Product);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else
                {
                    productEnseigneList.Enseignes = await db.Enseignes.ToListAsync();
                    return View(productEnseigneList);
                }
            }
            catch (Exception)
            {
                productEnseigneList.Enseignes = await db.Enseignes.ToListAsync();
                return View(productEnseigneList);
            }
            
        }

        // GET: Products/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Price,Number")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Product product = await db.Products.FindAsync(id);
            db.Products.Remove(product);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UsersTracker/Views/ClientProducts/Create.cshtml
@model UsersTracker.Entities.ClientProduct

@{
    ViewBag.Title = "Create";
}

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/bundles/JQueryUI")
    @Scripts.Render("~/bundles/AchatsCreate")
    @Styles.Render("~/Content/JQueryUIDatepicker-css")
}

<h2>Create</h2>

@if (ViewBag.Error != null)
{
    @Html.Label((String)ViewBag.Error, new { @class = "text-danger" });
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ClientProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdClient, "IdClient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdClient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdClient, "", new { @class = "text-danger" })
            </div>
            @Html.HiddenFor(model => model.Client.Id)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdProduct, "IdProduct", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProduct", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProduct, "", new { @class = "text-danger" })
            </div>
            @Html.HiddenFor(model => model.Product.Id)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BuyAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BuyAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BuyAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Valeur", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Label("0", htmlAttributes: new { @id = "labelCalc", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Acheter" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

UsersTracker/Views/ClientProducts/Delete.cshtml
@model UsersTracker.Entities.ClientProduct

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClientProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Client.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BuyAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BuyAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UsersTracker/Views/ClientProducts/Details.cshtml
@model UsersTracker.Entities.ClientProduct

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ClientProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Client.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BuyAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BuyAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UsersTracker/Views/ClientProducts/Edit.cshtml
@model UsersTracker.Entities.ClientProduct

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClientProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.IdClient, "IdClient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdClient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdClient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdProduct, "IdProduct", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProduct", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProduct, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BuyAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BuyAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BuyAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UsersTracker/Views/ClientProducts/Index.cshtml
@model IEnumerable<UsersTracker.Entities.ClientProduct>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Client.Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BuyAt)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Client.Firstname.ToString(), "Details/" + item.Id, "Clients")
        </td>
        <td>
            @Html.ActionLink(item.Product.Name.ToString(), "Details/" + item.Id, "Products")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BuyAt)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>